name: Build and deploy packge

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          node-version: '9.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test

      - name: Create the package
        run: dotnet pack --configuration Release

      - name: Publish the package
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json
